import { Palette, Language } from './types';

export const LANGUAGES: { code: Language; label: string }[] = [
  { code: 'zh-TW', label: '繁體中文' },
  { code: 'en', label: 'English' },
  { code: 'ja', label: '日本語' },
  { code: 'ko', label: '한국어' },
];

export const UI_TEXT = {
  'zh-TW': {
    title: 'Mood Palette',
    subtitle: 'AI 靈感配色',
    currentSelection: '目前配色',
    designSuggestions: '設計建議',
    exportJson: '匯出 PNG',
    placeholder: '輸入關鍵字 (例：復古底片、賽博龐克)...',
    generate: '生成配色',
    dreaming: '分析中...',
    footer: '讓色彩訴說故事。',
    error: '無法生成配色，請稍後再試。',
    visualize: '視覺化氛圍',
    painting: '繪製中...',
    trending: '熱門色系推薦',
    myPalettes: '已生成色系',
    backToHome: '返回主頁',
    noHistory: '尚未生成任何配色。試試上方的搜尋框吧！',
    heroTitle: '尋找你的完美色調',
    heroDesc: '輸入風格或情緒，讓 AI 為你調配專屬色盤。',
    adjust: '調整',
    done: '完成',
    delete: '刪除',
    imageInputPlaceholder: '輸入畫面關鍵詞 (例: 天空、城市、晴天)',
    imageInputLabel: '想在畫面中看到什麼？',
    addPalette: '新增配色',
    create: '建立',
    cancel: '取消',
    paletteName: '配色名稱',
    paletteDesc: '描述 (選填)',
    colorCodes: '輸入色碼 (Hex)',
    invalidHex: '色碼無效',
  },
  'en': {
    title: 'Mood Palette',
    subtitle: 'AI COLOR INSPIRATION',
    currentSelection: 'Current Palette',
    designSuggestions: 'Usage Guide',
    exportJson: 'Export PNG',
    placeholder: 'Enter keywords (e.g., Retro Film, Cyberpunk)...',
    generate: 'Generate',
    dreaming: 'Analyzing...',
    footer: 'Let colors tell the story.',
    error: 'Failed to generate palette. Please try again.',
    visualize: 'Visualize Mood',
    painting: 'Painting...',
    trending: 'Trending Palettes',
    myPalettes: 'Generated Palettes',
    backToHome: 'Back to Home',
    noHistory: 'No palettes generated yet. Try the search bar above!',
    heroTitle: 'Find Your Perfect Palette',
    heroDesc: 'Describe a style or mood, and let AI generate it for you.',
    adjust: 'Edit',
    done: 'Done',
    delete: 'Delete',
    imageInputPlaceholder: 'Keywords (e.g., Sky, City, Sunny)',
    imageInputLabel: 'What do you want to see?',
    addPalette: 'New Palette',
    create: 'Create',
    cancel: 'Cancel',
    paletteName: 'Palette Name',
    paletteDesc: 'Description (Optional)',
    colorCodes: 'Enter Hex Codes',
    invalidHex: 'Invalid Hex',
  },
  'ja': {
    title: 'Mood Palette',
    subtitle: 'AI カラーインスピレーション',
    currentSelection: '現在のパレット',
    designSuggestions: 'デザイン提案',
    exportJson: 'PNGを保存',
    placeholder: 'キーワードを入力 (例: レトロ、サイバーパンク)...',
    generate: '生成する',
    dreaming: '分析中...',
    footer: '色が物語を語る。',
    error: 'パレットを生成できませんでした。',
    visualize: 'ムードを視覚化',
    painting: '描画中...',
    trending: 'トレンドパレット',
    myPalettes: '生成されたパレット',
    backToHome: 'ホームに戻る',
    noHistory: 'まだパレットがありません。上の検索バーを試してください！',
    heroTitle: '完璧な色を見つける',
    heroDesc: 'スタイルやムードを入力して、AIに生成させましょう。',
    adjust: '編集',
    done: '完了',
    delete: '削除',
    imageInputPlaceholder: 'キーワード (例: 空、都市、晴れ)',
    imageInputLabel: '何を描きたいですか？',
    addPalette: '新規パレット',
    create: '作成',
    cancel: 'キャンセル',
    paletteName: 'パレット名',
    paletteDesc: '説明 (任意)',
    colorCodes: 'Hexコード入力',
    invalidHex: '無効なHex',
  },
  'ko': {
    title: 'Mood Palette',
    subtitle: 'AI 컬러 영감',
    currentSelection: '현재 팔레트',
    designSuggestions: '디자인 제안',
    exportJson: 'PNG 내보내기',
    placeholder: '키워드 입력 (예: 레트로, 사이버펑크)...',
    generate: '생성',
    dreaming: '분석 중...',
    footer: '색채로 이야기를 전하세요.',
    error: '팔레트를 생성하지 못했습니다.',
    visualize: '분위기 시각화',
    painting: '그리는 중...',
    trending: '인기 팔레트',
    myPalettes: '생성된 팔레트',
    backToHome: '홈으로 돌아가기',
    noHistory: '아직 생성된 팔레트가 없습니다. 위의 검색창을 이용해보세요!',
    heroTitle: '완벽한 팔레트 찾기',
    heroDesc: '스타일이나 분위기를 설명하면 AI가 생성해줍니다.',
    adjust: '편집',
    done: '완료',
    delete: '삭제',
    imageInputPlaceholder: '키워드 (예: 하늘, 도시, 맑음)',
    imageInputLabel: '무엇을 보고 싶으신가요?',
    addPalette: '새 팔레트',
    create: '만들기',
    cancel: '취소',
    paletteName: '팔레트 이름',
    paletteDesc: '설명 (선택)',
    colorCodes: 'Hex 코드 입력',
    invalidHex: '잘못된 Hex',
  },
};

// Top 10 Popular Palettes
export const POPULAR_PALETTES: Palette[] = [
  {
    id: 'nordic',
    name: 'Nordic Minimalism',
    description: 'Clean, airy, and functional.',
    designAdvice: 'Perfect for modern interiors, productivity apps, or lifestyle blogs.',
    colors: [
      { hex: '#F0F4F8', name: 'Ice Water' },
      { hex: '#D9E2EC', name: 'Pale Mist' },
      { hex: '#BCCCDC', name: 'Steel' },
      { hex: '#9FB3C8', name: 'Fjord' },
      { hex: '#829AB1', name: 'Slate' },
    ],
    createdAt: 1,
  },
  {
    id: 'boho',
    name: 'Earthy Boho',
    description: 'Warm, grounded, and organic.',
    designAdvice: 'Great for organic products, wedding themes, or cozy branding.',
    colors: [
      { hex: '#F7F1E3', name: 'Cream' },
      { hex: '#D1CCC0', name: 'Linen' },
      { hex: '#CC8E35', name: 'Mustard' },
      { hex: '#B33939', name: 'Terracotta' },
      { hex: '#2C3A47', name: 'Deep Forest' },
    ],
    createdAt: 2,
  },
  {
    id: 'cyberpunk',
    name: 'Cyberpunk Neon',
    description: 'High contrast, futuristic, and electric.',
    designAdvice: 'Ideal for gaming, tech startups, or nightlife events.',
    colors: [
      { hex: '#0B0C10', name: 'Void' },
      { hex: '#1F2833', name: 'Dark Metal' },
      { hex: '#C5C6C7', name: 'Silver' },
      { hex: '#66FCF1', name: 'Neon Cyan' },
      { hex: '#45A29E', name: 'Matrix' },
    ],
    createdAt: 3,
  },
  {
    id: 'pastel',
    name: 'Soft Pastels',
    description: 'Gentle, soothing, and dreamy.',
    designAdvice: 'Suitable for baby products, bakeries, or wellness apps.',
    colors: [
      { hex: '#FFD1DC', name: 'Cotton Candy' },
      { hex: '#FFECB3', name: 'Cream Puff' },
      { hex: '#C1E1C1', name: 'Mint' },
      { hex: '#AEC6CF', name: 'Baby Blue' },
      { hex: '#B39EB5', name: 'Lavender' },
    ],
    createdAt: 4,
  },
  {
    id: 'vintage',
    name: 'Vintage Film',
    description: 'Nostalgic, faded, and warm.',
    designAdvice: 'Use for photography portfolios, storytelling, or retro branding.',
    colors: [
      { hex: '#F4E1D2', name: 'Sepia Light' },
      { hex: '#E6C2BF', name: 'Faded Rose' },
      { hex: '#A89F91', name: 'Old Stone' },
      { hex: '#8C7B75', name: 'Worn Leather' },
      { hex: '#4A403A', name: 'Dark Coffee' },
    ],
    createdAt: 5,
  },
  {
    id: 'ocean',
    name: 'Ocean Breeze',
    description: 'Refreshing, calm, and trustworthy.',
    designAdvice: 'Excellent for travel agencies, water brands, or corporate identity.',
    colors: [
      { hex: '#E0FFFF', name: 'Foam' },
      { hex: '#AFEEEE', name: 'Turquoise' },
      { hex: '#48D1CC', name: 'Teal' },
      { hex: '#00CED1', name: 'Deep Sea' },
      { hex: '#008080', name: 'Abyss' },
    ],
    createdAt: 6,
  },
  {
    id: 'sunset',
    name: 'Golden Sunset',
    description: 'Warm gradients of evening light.',
    designAdvice: 'Captures attention for marketing headers or energetic brands.',
    colors: [
      { hex: '#FF7E5F', name: 'Coral' },
      { hex: '#FEB47B', name: 'Peach' },
      { hex: '#FFCC33', name: 'Golden Hour' },
      { hex: '#C71585', name: 'Magenta' },
      { hex: '#4B0082', name: 'Twilight' },
    ],
    createdAt: 7,
  },
  {
    id: 'forest',
    name: 'Deep Forest',
    description: 'Natural, mysterious, and calm.',
    designAdvice: 'Eco-friendly brands, outdoor gear, or camping apps.',
    colors: [
      { hex: '#DAD7CD', name: 'Sage' },
      { hex: '#A3B18A', name: 'Moss' },
      { hex: '#588157', name: 'Fern' },
      { hex: '#3A5A40', name: 'Pine' },
      { hex: '#344E41', name: 'Dark Wood' },
    ],
    createdAt: 8,
  },
  {
    id: 'luxury',
    name: 'Midnight Luxury',
    description: 'Sophisticated, dark, and gold.',
    designAdvice: 'High-end fashion, jewelry, or exclusive memberships.',
    colors: [
      { hex: '#000000', name: 'Onyx' },
      { hex: '#1C1C1C', name: 'Graphite' },
      { hex: '#333333', name: 'Charcoal' },
      { hex: '#D4AF37', name: 'Gold Leaf' },
      { hex: '#F1E5AC', name: 'Champagne' },
    ],
    createdAt: 9,
  },
  {
    id: 'corporate',
    name: 'Modern Corporate',
    description: 'Trustworthy, professional, and clean.',
    designAdvice: 'Finance, legal firms, or technology dashboards.',
    colors: [
      { hex: '#FFFFFF', name: 'White' },
      { hex: '#F5F5F5', name: 'Off White' },
      { hex: '#003366', name: 'Navy' },
      { hex: '#00509E', name: 'Royal Blue' },
      { hex: '#D3D3D3', name: 'Light Gray' },
    ],
    createdAt: 10,
  },
];

export const DEFAULT_PALETTES: Record<Language, Palette> = {
    // Keeping this for fallback type safety, though we mainly use POPULAR_PALETTES now
    'en': POPULAR_PALETTES[0],
    'zh-TW': POPULAR_PALETTES[0],
    'ja': POPULAR_PALETTES[0],
    'ko': POPULAR_PALETTES[0],
};